[tool.poetry]
name = "llms-from-scratch"
version = "0.1.0"
description = ""
authors = ["Xiangzhuang Shen <datahonor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pip = "^24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
